modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "test"
authors = "fayer3"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
test
'''

[[dependencies.examplemod]]
modId = "neoforge"
type = "required"
versionRange = "[21.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.21.3]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "test.mixins.json"
